export const countries = [
  { label: "United States", value: "US" },
  { label: "United Kingdom", value: "GB" },
  { label: "Canada", value: "CA" },
  { label: "Australia", value: "AU" },
  { label: "Germany", value: "DE" },
  { label: "France", value: "FR" },
  { label: "India", value: "IN" },
  { label: "Brazil", value: "BR" },
  { label: "Nigeria", value: "NG" },
  { label: "South Africa", value: "ZA" },
  { label: "China", value: "CN" },
  { label: "Japan", value: "JP" },
  { label: "South Korea", value: "KR" },
  { label: "Spain", value: "ES" },
  { label: "Italy", value: "IT" },
  { label: "Netherlands", value: "NL" },
  { label: "Sweden", value: "SE" },
  { label: "Switzerland", value: "CH" },
  { label: "Poland", value: "PL" },
  { label: "Mexico", value: "MX" },
  { label: "Argentina", value: "AR" },
  { label: "Colombia", value: "CO" },
  { label: "Egypt", value: "EG" },
  { label: "Kenya", value: "KE" },
  { label: "Ghana", value: "GH" },
  { label: "United Arab Emirates", value: "AE" },
  { label: "Saudi Arabia", value: "SA" },
  { label: "Singapore", value: "SG" },
  { label: "Indonesia", value: "ID" },
  { label: "Philippines", value: "PH" },
  { label: "Vietnam", value: "VN" },
  { label: "Turkey", value: "TR" },
].sort((a, b) => a.label.localeCompare(b.label));
